import SettingsIcon from "@mui/icons-material/Settings";
import ListAltIcon from "@mui/icons-material/ListAlt";
import TrainIcon from "@mui/icons-material/Train";
import PlaceIcon from "@mui/icons-material/Place";
import LinearScaleIcon from "@mui/icons-material/LinearScale";
import SwapHorizIcon from "@mui/icons-material/SwapHoriz";
import AppRegistrationIcon from "@mui/icons-material/AppRegistration";
import AdminPanelSettingsIcon from "@mui/icons-material/AdminPanelSettings";
import TableChartIcon from "@mui/icons-material/TableChart";
import PeopleIcon from "@mui/icons-material/People";
// import FingerprintIcon from "@mui/icons-material/Fingerprint";
// import LocationOnIcon from "@mui/icons-material/LocationOn";
// import ViewQuiltIcon from "@mui/icons-material/ViewQuilt";
// import BusinessIcon from "@mui/icons-material/Business";
// import BoltIcon from "@mui/icons-material/Bolt";
// import TrafficIcon from "@mui/icons-material/Traffic";
// import LinkIcon from "@mui/icons-material/Link";
// import SecurityIcon from "@mui/icons-material/Security";
// import InfoIcon from "@mui/icons-material/Info";

import { MenuItemType } from "./Menu";
import { LibraryBooks } from "@mui/icons-material";
const baseUrl = process.env.NEXT_PUBLIC_PROXY_BASE_URL || "";

export const getMenuOptions = (): MenuItemType[] => [
  {
    id: 100,
    label: "Σεμινάρια",
    href: `${baseUrl}/el/portal/seminaria`,
    icon: LibraryBooks,
    type: "link",
  },
  {
    id: 101,
    label: "Καλάθι",
    href: `${baseUrl}/el/portal/kalathi`,
    icon: ListAltIcon,
    type: "link",
  },
  {
    id: 102,
    label: "Υποβολή Αίτησης",
    href: `${baseUrl}/el/portal/ypovoli-aitisis`,
    icon: AppRegistrationIcon,
    type: "link",
  },
  {
    id: 103,
    label: "Δήλωση Δικαιολογητικών και Στοιχείων σε Επιμορφωτικά Προγράμματα",
    href: `${baseUrl}/el/portal/dilosi-dikaiologitikon`,
    icon: TableChartIcon,
    type: "link",
  },
  {
    id: 104,
    label: "Προσωποποίηση Λογαριασμού",
    href: `${baseUrl}/el/portal/prosopopoiisi-logariasmou`,
    icon: PeopleIcon,
    type: "link",
  },
  {
    id: 105,
    label: "Αξιολόγηση",
    href: `${baseUrl}/el/portal/axiologisi`,
    icon: SwapHorizIcon,
    type: "link",
  },
  {
    id: 106,
    label: "Απεργίες",
    href: `${baseUrl}/el/portal/apergies`,
    icon: TrainIcon,
    type: "link",
  },
  {
    id: 107,
    label: "WEBEX-ΕΚΠΑΙΔΕΥΣΕΙΣ",
    href: `${baseUrl}/el/portal/webex-ekpaideuseis`,
    icon: SettingsIcon,
    type: "link",
  },
  {
    id: 1,
    label: "Operational Point",
    type: "folder",
    icon: PlaceIcon,
    children: [
      {
        id: 4000,
        label: "ΕΓΓΡΑΦΕΣ",
        type: "link",
        icon: LibraryBooks,
        children: [],
        href: `${baseUrl}/el/records`,
      },
      // {
      //   id: 4001,
      //   label: "ΤΜΗΜΑ ΓΡΑΜΜΗΣ",
      //   type: "link",
      //   icon: LinearScaleIcon,
      //   children: [],
      //   href: `${baseUrl}/el/tmima-grammhs`,
      // },
      // {
      //   id: 4002,
      //   label: "ΤΡΟΧΙΑ ΚΥΚΛΟΦΟΡΙΑΣ", // Second Submenu
      //   type: "link",
      //   icon: TrainIcon,
      //   href: `${baseUrl}/el/troxia`,
      // },
      // {
      //   // Identity
      //   id: 4003,
      //   label: "Ταυτότητα",
      //   type: "link",
      //   icon: FingerprintIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/identity`,
      // },
      // {
      //   // Location
      //   id: 4004,
      //   label: "Τοποθεσία",
      //   type: "link",
      //   icon: LocationOnIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/location`,
      // },
      // {
      //   // Tracks
      //   id: 4005,
      //   label: "Τροχιές",
      //   type: "link",
      //   icon: TrainIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/tracks`,
      // },
      // {
      //   // Platforms
      //   id: 4006,
      //   label: "Αποβάθρες",
      //   type: "link",
      //   icon: ViewQuiltIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/platforms`,
      // },
      // {
      //   // Facilities
      //   id: 4007,
      //   label: "Εγκαταστάσεις",
      //   type: "link",
      //   icon: BusinessIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/facilities`,
      // },
      // {
      //   // ElectrificationSystems
      //   id: 4008,
      //   label: "Συστήματα Ηλεκτροδότησης",
      //   type: "link",
      //   icon: BoltIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/electrification-systems`,
      // },
      // {
      //   // SignallingAndControl
      //   id: 4009,
      //   label: "Σηματοδότηση και Έλεγχος",
      //   type: "link",
      //   icon: TrafficIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/signalling-and-control`,
      // },
      // {
      //   // Connections
      //   id: 4011,
      //   label: "Συνδέσεις",
      //   type: "link",
      //   icon: LinkIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/connections`,
      // },
      // {
      //   // SafetyAndCompliance
      //   id: 4012,
      //   label: "Ασφάλεια και Συμμόρφωση",
      //   type: "link",
      //   icon: SecurityIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/safety-and-compliance`,
      // },
      // {
      //   // Metadata
      //   id: 4013,
      //   label: "Metadata",
      //   type: "link",
      //   icon: InfoIcon,
      //   children: [],
      //   href: `${baseUrl}/el/operational-point/metadata`,
      // },
    ],
  },
  {
    id: 2,
    label: "S.O.L",
    href: `${baseUrl}/el/section-of-line`,
    icon: LinearScaleIcon,
    type: "link",
  },
  // {
  //   id: 3,
  //   label: "Ontology Setup(2)",
  //   type: "folder",
  //   icon: SettingsIcon,
  //   children: [
  //     {
  //       id: 101,
  //       label: "Ontology Item 1",
  //       href: `${baseUrl}/el/ontology/item1`,
  //       icon: SettingsIcon,
  //       type: "link",
  //     },
  //     {
  //       id: 102,
  //       label: "Ontology Item 2",
  //       href: `${baseUrl}/el/ontology/item2`,
  //       icon: SettingsIcon,
  //       type: "link",
  //     },
  //     {
  //       id: 103,
  //       label: "ERA 949 Railway Infrastructure Ontology",
  //       href: `${baseUrl}/el/ontology/era-949`,
  //       icon: SettingsIcon,
  //       type: "link",
  //     },
  //   ],
  // },
  // {
  //   id: 4,
  //   label: "LookUps ALL",
  //   href: `${baseUrl}/el/lookups/all`,
  //   icon: ListAltIcon,
  //   type: "link",
  // },
  {
    id: 5,
    label: "Master RINF",
    href: `${baseUrl}/el/master-rinf`,
    icon: TrainIcon,
    type: "link",
  },
  {
    id: 6,
    label: "Parameters",
    type: "folder",
    icon: SettingsIcon,
    href: `${baseUrl}/el/parameters`,
    children: [
      {
        id: 601,
        label: "GSM-R",
        href: `${baseUrl}/el/parameters/GSMR`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 602,
        label: "Operational Systems",
        href: `${baseUrl}/el/parameters/operational-systems`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 603,
        label: "Operational Point Types",
        href: `${baseUrl}/el/parameters/operational-point-types`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 604,
        label: "Operational Regime Types",
        href: `${baseUrl}/el/parameters/operational-regime-types`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 605,
        label: "Braking",
        href: `${baseUrl}/el/parameters/braking`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 606,
        label: "Coupling",
        href: `${baseUrl}/el/parameters/coupling`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 607,
        label: "Detection",
        href: `${baseUrl}/el/parameters/detection`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 608,
        label: "Energy",
        href: `${baseUrl}/el/parameters/energy`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 609,
        label: "Infrastructure & Operational Details",
        href: `${baseUrl}/el/parameters/infrastructure`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 610,
        label: "Vehicle Categories",
        href: `${baseUrl}/el/parameters/vehicle-categories`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 611,
        label: "Vehicle Authorisation & Type",
        href: `${baseUrl}/el/parameters/vehicle-authorisation`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 612,
        label: "Train Detection & Track Conditions",
        href: `${baseUrl}/el/parameters/track-condition`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 613,
        label: "Miscellaneous",
        href: `${baseUrl}/el/parameters/miscellaneous`,
        icon: ListAltIcon,
        type: "link",
      },
      {
        id: 614,
        label: "Legacy Radio Systems",
        href: `${baseUrl}/el/parameters/legacy-radio`,
        icon: ListAltIcon,
        type: "link",
      },
      //     {
      //       id: 613,
      //       label: "Param 13",
      //       href: `${baseUrl}/el/parameters/1/13`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 614,
      //       label: "Param 14",
      //       href: `${baseUrl}/el/parameters/1/14`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 615,
      //       label: "Param 15",
      //       href: `${baseUrl}/el/parameters/1/15`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 616,
      //       label: "Param 16",
      //       href: `${baseUrl}/el/param-lookups/1/16`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 617,
      //       label: "Param 17",
      //       href: `${baseUrl}/el/param-lookups/1/17`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 618,
      //       label: "Param 18",
      //       href: `${baseUrl}/el/param-lookups/1/18`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 619,
      //       label: "Param 19",
      //       href: `${baseUrl}/el/param-lookups/1/19`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 620,
      //       label: "Param 20",
      //       href: `${baseUrl}/el/param-lookups/1/20`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //   ],
      // },
      // {
      //   id: 7,
      //   label: "2.Param-LookUPs(15)",
      //   type: "folder",
      //   icon: Filter2Icon,
      //   children: [
      //     {
      //       id: 701,
      //       label: "Param 1",
      //       href: `${baseUrl}/el/param-lookups/2/1`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 702,
      //       label: "Param 2",
      //       href: `${baseUrl}/el/param-lookups/2/2`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 703,
      //       label: "Param 3",
      //       href: `${baseUrl}/el/param-lookups/2/3`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 704,
      //       label: "Param 4",
      //       href: `${baseUrl}/el/param-lookups/2/4`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 705,
      //       label: "Param 5",
      //       href: `${baseUrl}/el/param-lookups/2/5`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 706,
      //       label: "Param 6",
      //       href: `${baseUrl}/el/param-lookups/2/6`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 707,
      //       label: "Param 7",
      //       href: `${baseUrl}/el/param-lookups/2/7`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 708,
      //       label: "Param 8",
      //       href: `${baseUrl}/el/param-lookups/2/8`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 709,
      //       label: "Param 9",
      //       href: `${baseUrl}/el/param-lookups/2/9`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 710,
      //       label: "Param 10",
      //       href: `${baseUrl}/el/param-lookups/2/10`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 711,
      //       label: "Param 11",
      //       href: `${baseUrl}/el/param-lookups/2/11`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 712,
      //       label: "Param 12",
      //       href: `${baseUrl}/el/param-lookups/2/12`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 713,
      //       label: "Param 13",
      //       href: `${baseUrl}/el/param-lookups/2/13`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 714,
      //       label: "Param 14",
      //       href: `${baseUrl}/el/param-lookups/2/14`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 715,
      //       label: "Param 15",
      //       href: `${baseUrl}/el/param-lookups/2/15`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //   ],
      // },
      // {
      //   id: 8,
      //   label: "3.Param-LookUPs(20)",
      //   type: "folder",
      //   icon: Filter3Icon,
      //   children: [
      //     {
      //       id: 801,
      //       label: "Param 1",
      //       href: `${baseUrl}/el/param-lookups/3/1`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 802,
      //       label: "Param 2",
      //       href: `${baseUrl}/el/param-lookups/3/2`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 803,
      //       label: "Param 3",
      //       href: `${baseUrl}/el/param-lookups/3/3`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 804,
      //       label: "Param 4",
      //       href: `${baseUrl}/el/param-lookups/3/4`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 805,
      //       label: "Param 5",
      //       href: `${baseUrl}/el/param-lookups/3/5`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 806,
      //       label: "Param 6",
      //       href: `${baseUrl}/el/param-lookups/3/6`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 807,
      //       label: "Param 7",
      //       href: `${baseUrl}/el/param-lookups/3/7`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 808,
      //       label: "Param 8",
      //       href: `${baseUrl}/el/param-lookups/3/8`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 809,
      //       label: "Param 9",
      //       href: `${baseUrl}/el/param-lookups/3/9`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 810,
      //       label: "Param 10",
      //       href: `${baseUrl}/el/param-lookups/3/10`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 811,
      //       label: "Param 11",
      //       href: `${baseUrl}/el/param-lookups/3/11`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 812,
      //       label: "Param 12",
      //       href: `${baseUrl}/el/param-lookups/3/12`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 813,
      //       label: "Param 13",
      //       href: `${baseUrl}/el/param-lookups/3/13`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 814,
      //       label: "Param 14",
      //       href: `${baseUrl}/el/param-lookups/3/14`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 815,
      //       label: "Param 15",
      //       href: `${baseUrl}/el/param-lookups/3/15`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 816,
      //       label: "Param 16",
      //       href: `${baseUrl}/el/param-lookups/3/16`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 817,
      //       label: "Param 17",
      //       href: `${baseUrl}/el/param-lookups/3/17`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 818,
      //       label: "Param 18",
      //       href: `${baseUrl}/el/param-lookups/3/18`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 819,
      //       label: "Param 19",
      //       href: `${baseUrl}/el/param-lookups/3/19`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 820,
      //       label: "Param 20",
      //       href: `${baseUrl}/el/param-lookups/3/20`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //   ],
      // },
      // {
      //   id: 9,
      //   label: "4.Param-LookUPs(18)",
      //   type: "folder",
      //   icon: Filter4Icon,
      //   children: [
      //     {
      //       id: 901,
      //       label: "Param 1",
      //       href: `${baseUrl}/el/param-lookups/4/1`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 902,
      //       label: "Param 2",
      //       href: `${baseUrl}/el/param-lookups/4/2`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 903,
      //       label: "Param 3",
      //       href: `${baseUrl}/el/param-lookups/4/3`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 904,
      //       label: "Param 4",
      //       href: `${baseUrl}/el/param-lookups/4/4`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 905,
      //       label: "Param 5",
      //       href: `${baseUrl}/el/param-lookups/4/5`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 906,
      //       label: "Param 6",
      //       href: `${baseUrl}/el/param-lookups/4/6`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 907,
      //       label: "Param 7",
      //       href: `${baseUrl}/el/param-lookups/4/7`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 908,
      //       label: "Param 8",
      //       href: `${baseUrl}/el/param-lookups/4/8`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 909,
      //       label: "Param 9",
      //       href: `${baseUrl}/el/param-lookups/4/9`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 910,
      //       label: "Param 10",
      //       href: `${baseUrl}/el/param-lookups/4/10`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 911,
      //       label: "Param 11",
      //       href: `${baseUrl}/el/param-lookups/4/11`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 912,
      //       label: "Param 12",
      //       href: `${baseUrl}/el/param-lookups/4/12`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 913,
      //       label: "Param 13",
      //       href: `${baseUrl}/el/param-lookups/4/13`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 914,
      //       label: "Param 14",
      //       href: `${baseUrl}/el/param-lookups/4/14`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 915,
      //       label: "Param 15",
      //       href: `${baseUrl}/el/param-lookups/4/15`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 916,
      //       label: "Param 16",
      //       href: `${baseUrl}/el/param-lookups/4/16`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 917,
      //       label: "Param 17",
      //       href: `${baseUrl}/el/param-lookups/4/17`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
      //     {
      //       id: 918,
      //       label: "Param 18",
      //       href: `${baseUrl}/el/param-lookups/4/18`,
      //       icon: ListAltIcon,
      //       type: "link",
      //     },
    ],
  },
  {
    id: 10,
    label: "ΚΙΝΗΣΕΙΣ ΧΡΗΣΤΩΝ",
    href: `${baseUrl}/el/user-actions`,
    icon: SwapHorizIcon,
    type: "link",
  },
  {
    id: 11,
    label: "REGISTRATIONS",
    href: `${baseUrl}/el/registrations`,
    icon: AppRegistrationIcon,
    type: "link",
  },
  {
    id: 12,
    label: "ADMINISTRATION",
    type: "folder",
    icon: AdminPanelSettingsIcon,
    children: [
      {
        id: 1201,
        label: "Admin Item 1",
        href: `${baseUrl}/el/admin/item1`,
        icon: SettingsIcon,
        type: "link",
      },
      {
        id: 1202,
        label: "Admin Item 2",
        href: `${baseUrl}/el/admin/item2`,
        icon: PeopleIcon,
        type: "link",
      },
      {
        id: 1203,
        label: "Admin Item 3",
        href: `${baseUrl}/el/admin/item3`,
        icon: TableChartIcon,
        type: "link",
      },
    ],
  },

  {
    id: 14,
    label: "USERS",
    href: `${baseUrl}/el/users`,
    icon: PeopleIcon,
    type: "link",
  },
];
